# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.secretsName" $ }}
  namespace: {{ template "common.namespace" $ }}
data:
  POSTGRES_USER: {{ .Values.auth.username | b64enc | quote }}
  POSTGRES_DB: {{ .Values.auth.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
