{{- if .Values.deployOtelCollector }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-otel-config" (include "common.name" .) }}
  namespace: {{ template "common.namespace" $ }}
data:
  otel-collector-config.yaml: |
    exporters:
      otlp:
        endpoint: ${env:OLTP_ENDPOINT}
        headers:
          Authorization: pat ${env:HASURA_DDN_PAT}
    processors:
      batch: {}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        logs:
          exporters:
            - otlp
          processors:
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - otlp
          processors:
            - batch
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
          processors:
            - batch
          receivers:
            - otlp
{{- end }}
